### ISSUE TITLE
Scala Steward job is failing for the repo

### ISSUE THREAD

**Issue by tgodzik** [blackdoor/jose#55]
It seems that it might be an issue with the mill integration, updating mill version might help. The full log is:
```
java.io.IOException: 'mill -i -p /opt/workspace/repos/blackdoor/jose/scala-steward.sc show org.scalasteward.mill.plugin.StewardPlugin/extractDeps' exited with code 1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0

  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
  3 60.3M    3 2399k    0     0  1396k      0  0:00:44  0:00:01  0:00:43 2309k
 50 60.3M   50 30.6M    0     0  11.4M      0  0:00:05  0:00:02  0:00:03 15.3M
100 60.3M  100 60.3M    0     0  17.8M      0  0:00:03  0:00:03 --:--:-- 22.4M
Downloading https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_mill0.9_2.13/0.17.1/scala-steward-mill-plugin_mill0.9_2.13-0.17.1.pom
Downloaded https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_mill0.9_2.13/0.17.1/scala-steward-mill-plugin_mill0.9_2.13-0.17.1.pom
Downloading https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_mill0.9_2.13/0.17.1/scala-steward-mill-plugin_mill0.9_2.13-0.17.1.jar
Downloading https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_mill0.9_2.13/0.17.1/scala-steward-mill-plugin_mill0.9_2.13-0.17.1-sources.jar
Downloaded https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_mill0.9_2.13/0.17.1/scala-steward-mill-plugin_mill0.9_2.13-0.17.1.jar
Downloaded https://repo1.maven.org/maven2/org/scala-steward/scala-steward-mill-plugin_mill0.9_2.13/0.17.1/scala-steward-mill-plugin_mill0.9_2.13-0.17.1-sources.jar
Compiling /opt/workspace/repos/blackdoor/jose/scala-steward.sc
Compiling /opt/workspace/repos/blackdoor/jose/build.sc
[1/1] show 
Exception in thread "main" java.lang.NoSuchMethodError: 'void mainargs.arg.<init>(java.lang.String, char, java.lang.String, boolean)'
	at org.scalasteward.mill.plugin.StewardPlugin$.$anonfun$millDiscover$1(StewardPlugin.scala:86)
	at org.scalasteward.mill.plugin.StewardPlugin$.millDiscover$lzycompute(StewardPlugin.scala:86)
	at org.scalasteward.mill.plugin.StewardPlugin$.millDiscover(StewardPlugin.scala:86)
	at mill.main.RunScript$.$anonfun$resolveTasks$7(RunScript.scala:183)
	at scala.util.Either.map(Either.scala:382)
	at mill.main.RunScript$.$anonfun$resolveTasks$6(RunScript.scala:169)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at mill.main.RunScript$.$anonfun$resolveTasks$5(RunScript.scala:168)
	at scala.util.Either.flatMap(Either.scala:352)
	at mill.main.RunScript$.resolveTasks(RunScript.scala:165)
	at mill.main.RunScript$.$anonfun$resolveTasks$2(RunScript.scala:138)
	at scala.collection.immutable.List.map(List.scala:246)
	at scala.collection.immutable.List.map(List.scala:79)
	at mill.main.RunScript$.$anonfun$resolveTasks$1(RunScript.scala:137)
	at scala.util.Either.flatMap(Either.scala:352)
	at mill.main.RunScript$.resolveTasks(RunScript.scala:136)
	at mill.main.RunScript$.evaluateTasks(RunScript.scala:241)
	at mill.main.MainModule$.evaluateTasks(MainModule.scala:51)
	at mill.main.MainModule.$anonfun$show$1(MainModule.scala:236)
	at mill.define.Applicative$Applyer.$anonfun$zipMap$1(Applicative.scala:35)
	at mill.define.Task$MappedDest.evaluate(Task.scala:396)
	at mill.eval.Evaluator.$anonfun$evaluateGroup$13(Evaluator.scala:496)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withErr(Console.scala:193)
	at mill.eval.Evaluator.$anonfun$evaluateGroup$12(Evaluator.scala:496)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withOut(Console.scala:164)
	at mill.eval.Evaluator.$anonfun$evaluateGroup$11(Evaluator.scala:495)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at scala.Console$.withIn(Console.scala:227)
	at mill.eval.Evaluator.$anonfun$evaluateGroup$8(Evaluator.scala:494)
	at mill.eval.Evaluator.$anonfun$evaluateGroup$8$adapted(Evaluator.scala:445)
	at scala.collection.immutable.Vector.foreach(Vector.scala:1856)
	at mill.eval.Evaluator.evaluateGroup(Evaluator.scala:445)
	at mill.eval.Evaluator.$anonfun$evaluateGroupCached$13(Evaluator.scala:342)
	at scala.util.DynamicVariable.withValue(DynamicVariable.scala:59)
	at mill.eval.Evaluator.evaluateGroupCached(Evaluator.scala:333)
	at mill.eval.Evaluator.$anonfun$sequentialEvaluate$2(Evaluator.scala:116)
	at scala.collection.IterableOnceOps.foreach(IterableOnce.scala:563)
	at scala.collection.IterableOnceOps.foreach$(IterableOnce.scala:561)
	at scala.collection.AbstractIterator.foreach(Iterator.scala:1288)
	at mill.eval.Evaluator.sequentialEvaluate(Evaluator.scala:93)
	at mill.eval.Evaluator.evaluate(Evaluator.scala:79)
	at mill.main.RunScript$.evaluate(RunScript.scala:256)
	at mill.main.RunScript$.$anonfun$evaluateTasks$1(RunScript.scala:243)
	at scala.util.Either.map(Either.scala:382)
	at mill.main.RunScript$.evaluateTasks(RunScript.scala:241)
	at mill.main.RunScript$.$anonfun$runScript$4(RunScript.scala:69)
	at ammonite.util.Res$Success.flatMap(Res.scala:62)
	at mill.main.RunScript$.runScript(RunScript.scala:68)
	at mill.main.MainRunner.$anonfun$runScript$1(MainRunner.scala:119)
	at mill.main.MainRunner.watchLoop2(MainRunner.scala:68)
	at mill.main.MainRunner.runScript(MainRunner.scala:94)
	at mill.MillMain$.main0(MillMain.scala:322)
	at mill.MillMain$.main(MillMain.scala:109)
	at mill.MillMain.main(MillMain.scala)

	at org.scalasteward.core.io.process$.$anonfun$slurp$9(process.scala:54)
	at org.scalasteward.core.io.process$.$anonfun$slurp$9$adapted(process.scala:50)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at modify @ fs2.internal.Scope.close(Scope.scala:262)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at rethrow$extension @ fs2.Compiler$Target.$anonfun$compile$1(Compiler.scala:157)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
	at flatMap @ fs2.Pull$.$anonfun$compile$21(Pull.scala:1209)
	at update @ fs2.internal.Scope.releaseChildScope(Scope.scala:224)
	at flatMap @ fs2.Compiler$Target.flatMap(Compiler.scala:163)
2022-12-21 09:12:49,266 INFO  ──────────── Total time: Steward blackdoor/jose: 31s 959ms ────────────

```

**Comment by nrktkt** [comment]
Scala steward is only supporting 0.9.x?
I'm merging https://github.com/blackdoor/jose/pull/56, let me know if that resolves it.

**Comment by tgodzik** [comment]
There was a similar issue in coursier/dependency repo and this PR should solve it: https://github.com/coursier/dependency/pull/16

So might not be the version of mill but some issue with the mill plugin.

**Comment by tgodzik** [comment]
Anyway, let's see if the mill update helped. We run the Scala Steward job every two days.

**Comment by nrktkt** [comment]
I think the update helped, we have PRs coming in now.
Thanks for the heads up on this!
